apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-frontend.fullname" . }}
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
# process .env file
{{- range $line := splitList "\n" .Values.envFile }}
  {{- $kv := splitList "=" $line -}}
  {{- $k := first $kv -}}
  {{- if $k }}
  {{ $k }}: {{ last $kv | b64enc | quote }}
  {{- end }}

{{- end }}
# process .env file which extends and overrides
{{- if .Values.extraEnvFile }}
{{- range $line := splitList "\n" .Values.extraEnvFile }}
  {{- $kv := splitList "=" $line -}}
  {{- $k := first $kv -}}
  {{- if $k }}
  {{ $k }}: {{ last $kv | b64enc | quote }}
  {{- end }}

{{- end }}
{{- end }}